const $=s=>document.querySelector(s),state={meta:null,page:1,pageSize:50,total:0,selected:new Set(),timer:null};
const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(n??0);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=()=>new URLSearchParams({state:$('#state').value,county:$('#county').value,use:$('#use').value,search:$('#search').value,page:state.page,pageSize:state.pageSize});
async function json(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.style.background=error?'#421d2a':'#16352d';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function options(el,values,label){el.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
async function loadMeta(){state.meta=await json('/api/meta');options($('#state'),state.meta.states,'All states');options($('#use'),state.meta.uses,'All uses');buildHeader();buildForm();updateSave(state.meta.dirty)}
function filterQuery(){const p=params();p.delete('page');p.delete('pageSize');return p.toString()}
async function refresh(){try{const q=params(),[records,stats,groups]=await Promise.all([json('/api/records?'+q),json('/api/stats?'+filterQuery()),json('/api/group?'+filterQuery()+'&by='+encodeURIComponent($('#group').value))]);state.total=records.total;renderRows(records);renderKpis(stats);renderBars(groups);renderDonut(stats);updateSave(true);$('#viewSummary').textContent=`${fmt(records.total)} matching records · sorted by EV share using merge sort`;$('#recordCount').textContent=`(${fmt(records.total)})`;}catch(e){toast(e.message,true)}}
function buildHeader(){$('#thead').innerHTML='<tr><th><input id="selectAll" type="checkbox" aria-label="Select all visible records"></th>'+state.meta.header.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr>';$('#selectAll').onchange=e=>{document.querySelectorAll('#tbody input').forEach(box=>{box.checked=e.target.checked;box.dispatchEvent(new Event('change'))})}}
function renderRows(result){state.selected.clear();updateSelected();$('#tbody').innerHTML=result.records.map(r=>`<tr data-id="${r.id}"><td><input type="checkbox" aria-label="Select record"></td>${r.values.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="99">No matching records</td></tr>';document.querySelectorAll('#tbody tr[data-id]').forEach(tr=>{const box=tr.querySelector('input');box.onchange=()=>{box.checked?state.selected.add(tr.dataset.id):state.selected.delete(tr.dataset.id);tr.classList.toggle('selected',box.checked);updateSelected()}});const pages=Math.max(1,Math.ceil(result.total/result.pageSize));$('#pageInfo').textContent=`Page ${result.page} of ${pages}`;$('#prev').disabled=result.page<=1;$('#next').disabled=result.page>=pages}
function renderKpis(s){const data=[['Records',fmt(s.records),'matching rows','#41e6b4'],['Weighted EV share',s.weightedEvPercent.toFixed(2)+'%','EVs ÷ total vehicles','#34b8ff'],['Total EVs',fmt(s.evTotal),'BEV + PHEV','#9175ff'],['Battery EVs',fmt(s.bev),'fully electric','#41e6b4'],['Plug-in hybrids',fmt(s.phev),'PHEV total','#f2b84b'],['Top state',s.topState,'highest weighted share','#34b8ff']];$('#kpis').innerHTML=data.map(([l,v,d,c])=>`<article class="kpi" style="--accent:${c}"><span>${l}</span><strong>${esc(v)}</strong><span>${esc(d)}</span></article>`).join('');const dash=Math.min(302,s.weightedEvPercent/100*302);$('#meter').style.strokeDasharray=`${dash} 302`;$('#pulseValue').textContent=s.weightedEvPercent.toFixed(1)+'%';$('#pulseTotal').textContent=fmt(s.evTotal)+' EVs'}
function renderBars(rows){$('#barTitle').textContent=`Top ${$('#group').selectedOptions[0].text.toLowerCase()} groups by weighted EV share`;const svg=$('#barChart'),w=760,h=245,p={l:48,r:15,t:20,b:58},max=Math.max(1,...rows.map(x=>x.value)),bw=(w-p.l-p.r)/Math.max(1,rows.length);let out=`<defs><linearGradient id="barGradient" x1="0" y1="1" x2="0" y2="0"><stop stop-color="#228f91"/><stop offset="1" stop-color="#41e6b4"/></linearGradient></defs>`;[0,.25,.5,.75,1].forEach(t=>{const y=p.t+(h-p.t-p.b)*(1-t);out+=`<line class="grid-line" x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}"/><text class="axis-label" x="${p.l-7}" y="${y+3}" text-anchor="end">${(max*t).toFixed(1)}%</text>`});rows.forEach((r,i)=>{const bh=r.value/max*(h-p.t-p.b),x=p.l+i*bw+bw*.17,y=h-p.b-bh;out+=`<rect class="bar" x="${x}" y="${y}" width="${bw*.66}" height="${bh}" rx="5"><title>${esc(r.label)}: ${r.value.toFixed(2)}%</title></rect><text class="value-label" x="${x+bw*.33}" y="${y-5}" text-anchor="middle">${r.value.toFixed(1)}</text><text class="axis-label" transform="translate(${x+bw*.33},${h-p.b+9}) rotate(35)" text-anchor="start">${esc(r.label.length>15?r.label.slice(0,14)+'…':r.label)}</text>`});svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=out}
function renderDonut(s){const total=s.bev+s.phev||1,bev=s.bev/total,phev=s.phev/total,r=72,c=2*Math.PI*r;$('#donutChart').innerHTML=`<circle cx="110" cy="110" r="${r}" fill="none" stroke="#1d3046" stroke-width="25"/><circle cx="110" cy="110" r="${r}" fill="none" stroke="#41e6b4" stroke-width="25" stroke-dasharray="${c*bev} ${c}" transform="rotate(-90 110 110)"/><circle cx="110" cy="110" r="${r}" fill="none" stroke="#9175ff" stroke-width="25" stroke-dasharray="${c*phev} ${c}" stroke-dashoffset="${-c*bev}" transform="rotate(-90 110 110)"/><text x="110" y="105" text-anchor="middle" fill="#ecf7ff" font-size="22" font-weight="800">${(bev*100).toFixed(1)}%</text><text x="110" y="126" text-anchor="middle" fill="#8fa7bd" font-size="10">BATTERY EV</text>`;$('#donutLegend').innerHTML=`<p><span style="color:#41e6b4">●</span> Battery EV<b>${fmt(s.bev)}</b></p><p><span style="color:#9175ff">●</span> Plug-in hybrid<b>${fmt(s.phev)}</b></p>`}
function updateSelected(){$('#selectedCount').textContent=`${state.selected.size} selected`;$('#delete').disabled=!state.selected.size}
function updateSave(dirty){$('#saveStatus').textContent=dirty?'Unsaved view':'Saved';$('#saveStatus').classList.toggle('dirty',dirty)}
function buildForm(){$('#formFields').innerHTML=state.meta.header.map((h,i)=>`<label>${esc(h)}<input name="c${i}" ${/state|county/i.test(h)?'required':''} ${/vehicles|percent/i.test(h)?'inputmode="decimal"':''}></label>`).join('')}
async function updateCounties(){const st=$('#state').value;if(!st){options($('#county'),[],'All counties');$('#county').disabled=true}else{options($('#county'),await json('/api/records?counties='+encodeURIComponent(st)),'All counties');$('#county').disabled=false}}
function filtered(){state.page=1;clearTimeout(state.timer);state.timer=setTimeout(refresh,180)}
$('#state').onchange=async()=>{await updateCounties();filtered()};['county','use','group'].forEach(id=>$('#'+id).onchange=filtered);$('#search').oninput=filtered;
$('#clear').onclick=async()=>{$('#state').value='';$('#county').value='';$('#county').disabled=true;$('#use').value='';$('#search').value='';$('#group').value='state';state.page=1;await refresh()};
$('#refresh').onclick=$('#pulse').onclick=refresh;$('#prev').onclick=()=>{state.page--;refresh()};$('#next').onclick=()=>{state.page++;refresh()};
$('#add').onclick=()=>{$('#formError').textContent='';$('#addDialog').showModal()};$('#closeDialog').onclick=$('#cancelAdd').onclick=()=>$('#addDialog').close();
$('#addForm').onsubmit=async e=>{e.preventDefault();try{await json('/api/records',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(e.target))});e.target.reset();$('#addDialog').close();toast('Record added and indexed');await loadMeta();await refresh()}catch(err){$('#formError').textContent=err.message}};
$('#delete').onclick=async()=>{if(!confirm(`Delete ${state.selected.size} selected record(s)? This change is not permanent until Save.`))return;try{for(const id of state.selected)await json('/api/records?id='+encodeURIComponent(id),{method:'DELETE'});toast('Selected records deleted');await loadMeta();await refresh()}catch(e){toast(e.message,true)}};
$('#save').onclick=async()=>{try{await json('/api/save',{method:'POST'});updateSave(false);toast('Database saved safely')}catch(e){toast(e.message,true)}};
$('#fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!confirm(`Replace the working database with ${file.name}?`))return;try{const text=await file.text();const result=await json('/api/import',{method:'POST',headers:{'Content-Type':'text/csv'},body:text});toast(`Imported ${fmt(result.rows)} rows`);await loadMeta();await refresh()}catch(err){toast(err.message,true)}finally{e.target.value=''}};
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('#save').click()}if(e.key==='Escape'&&$('#addDialog').open)$('#addDialog').close()});
(async()=>{try{await loadMeta();await refresh()}catch(e){toast(e.message,true);$('#viewSummary').textContent='Could not load the database.'}})();

let connectionWasLost=false;
setInterval(async()=>{try{await json('/api/health');if(connectionWasLost){connectionWasLost=false;toast('Connection restored');await loadMeta();await refresh()}}catch(e){connectionWasLost=true;$('#viewSummary').textContent='Connection lost. Reopen VoltVista, then this page will reconnect automatically.';toast('VoltVista connection lost',true)}},15000);
